#:schema node_modules/wrangler/config-schema.json
name = "ottodev"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = true

[vars]
ANTHROPIC_API_KEY = "hf_rAnDoMdUmMyApIkEy4OtToDeV"
OPENAI_API_KEY = "sk-proj-_rAnDoMdUmMyApIkEy4OtToDeV"
GOOGLE_GENERATIVE_AI_API_KEY = "_rAnDoMdUmMyApIkEy4OtToDeV"
HuggingFace_API_KEY = "hf__rAnDoMdUmMyApIkEy4OtToDeV"

[env.production]
[env.production.vars]
ANTHROPIC_API_KEY = "hf_rAnDoMdUmMyApIkEy4OtToDeV"
OPENAI_API_KEY = "sk-proj-_rAnDoMdUmMyApIkEy4OtToDeV"
GOOGLE_GENERATIVE_AI_API_KEY = "_rAnDoMdUmMyApIkEy4OtToDeV"
HuggingFace_API_KEY = "hf__rAnDoMdUmMyApIkEy4OtToDeV"