jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Push Changes to Fork
      - name: Push Changes to Fork
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push https://${TOKEN}@github.com/Cyopsys/ottodev.git main

      # Step 3: Merges upstream changes (if any)
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/coleam00/bolt.new-any-llm
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream changes" || echo "Merge conflict detected or no changes"

      # Step 4: Push changes to your fork
      - name: Push Changes to Fork
        run: |
          git push origin main

      # Step 5: Install dependencies using pnpm
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # Step 6: Build the project (using whatever build tool, like Vite, Remix)
      - name: Build project
        run: |
          pnpm run build

      # Step 7: Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        run: |
          echo "Deploying to Cloudflare Pages..."
          # Add your deployment command here, e.g., wrangler publish
