name: Sync, Build, and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (should be from root where package.json is)
      - name: Install dependencies
        run: |
          npm install

      # Step 3: Build the project (using whatever build tool, like Vite, Remix)
      - name: Build project
        run: |
          npm run build

      # Step 4: Deploy to Cloudflare Pages (can use wrangler or any deploy command)
      - name: Deploy to Cloudflare Pages
        run: |
          echo "Deploying to Cloudflare Pages..."
